//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web365.App_LocalResources.ResourceLanguage", typeof(ResourceLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự kiện nổi bật.
        /// </summary>
        public static string AchievementHighlight {
            get {
                return ResourceManager.GetString("AchievementHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả sự kiện.
        /// </summary>
        public static string AllAchievementHighlight {
            get {
                return ResourceManager.GetString("AllAchievementHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bởi.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng lại.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận xét về chúng tôi.
        /// </summary>
        public static string CommentsAboutUs {
            get {
                return ResourceManager.GetString("CommentsAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực hoạt động.
        /// </summary>
        public static string CompanyBusiness {
            get {
                return ResourceManager.GetString("CompanyBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string ContacInfo {
            get {
                return ResourceManager.GetString("ContacInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ ngay.
        /// </summary>
        public static string ContactNow {
            get {
                return ResourceManager.GetString("ContactNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện tài liệu.
        /// </summary>
        public static string DocumentLibrary {
            get {
                return ResourceManager.GetString("DocumentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải xuống.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập email.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần nhập đúng định dạng email.
        /// </summary>
        public static string EmailValidate {
            get {
                return ResourceManager.GetString("EmailValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa tìm kiếm ....
        /// </summary>
        public static string EnterSearchKeyword {
            get {
                return ResourceManager.GetString("EnterSearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu nổi bật.
        /// </summary>
        public static string FeaturedDocuments {
            get {
                return ResourceManager.GetString("FeaturedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dự án tiêu biểu.
        /// </summary>
        public static string FeaturedProject {
            get {
                return ResourceManager.GetString("FeaturedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video nổi bật.
        /// </summary>
        public static string FeaturedVideos {
            get {
                return ResourceManager.GetString("FeaturedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh nổi bật.
        /// </summary>
        public static string FeatureImages {
            get {
                return ResourceManager.GetString("FeatureImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to từ.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi cung cấp các kỹ sư và các nhà xây dựng tốt nhất để thực hiện ước mơ của bạn trở thành sự thật..
        /// </summary>
        public static string HomeContactContent {
            get {
                return ResourceManager.GetString("HomeContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có cần chuyên gia để dự án và xây dựng ngôi nhà mơ ước của bạn?.
        /// </summary>
        public static string HomeContactTitle {
            get {
                return ResourceManager.GetString("HomeContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng dụng kết nối thông minh G-Store.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới nhất.
        /// </summary>
        public static string LastestNews {
            get {
                return ResourceManager.GetString("LastestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung tin nhắn.
        /// </summary>
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức &amp; Sự kiện.
        /// </summary>
        public static string NewsAndEvents {
            get {
                return ResourceManager.GetString("NewsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi! Chúng tôi không thể tìm thấy trang mà bạn yêu cầu..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết cùng chuyên mục.
        /// </summary>
        public static string OtherNews {
            get {
                return ResourceManager.GetString("OtherNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dự án khác.
        /// </summary>
        public static string OtherProjects {
            get {
                return ResourceManager.GetString("OtherProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án của chúng tôi.
        /// </summary>
        public static string OurProject {
            get {
                return ResourceManager.GetString("OurProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DỊCH VỤ CỦA CHÚNG TÔI.
        /// </summary>
        public static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác của chúng tôi.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện hình ảnh.
        /// </summary>
        public static string PictureLibrary {
            get {
                return ResourceManager.GetString("PictureLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bất động sản.
        /// </summary>
        public static string ProjectBDS {
            get {
                return ResourceManager.GetString("ProjectBDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công trình dân dụng.
        /// </summary>
        public static string ProjectCTDD {
            get {
                return ResourceManager.GetString("ProjectCTDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết dự án.
        /// </summary>
        public static string ProjectDetail {
            get {
                return ResourceManager.GetString("ProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao thông.
        /// </summary>
        public static string ProjectGT {
            get {
                return ResourceManager.GetString("ProjectGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin dự án.
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string ProjectKHAC {
            get {
                return ResourceManager.GetString("ProjectKHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dự án đang triển khai.
        /// </summary>
        public static string ProjectOnGoing {
            get {
                return ResourceManager.GetString("ProjectOnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát triển khu công nghiệp.
        /// </summary>
        public static string ProjectPTKCN {
            get {
                return ResourceManager.GetString("ProjectPTKCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dự án.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương mại &amp; dịch vụ.
        /// </summary>
        public static string ProjectTMDV {
            get {
                return ResourceManager.GetString("ProjectTMDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi, không có gì phù hợp tiêu chí tìm kiếm của bạn. Hãy thử sử dụng các từ tổng quát hơn để có được kết quả hơn..
        /// </summary>
        public static string SearchResultNotFound {
            get {
                return ResourceManager.GetString("SearchResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Email.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi mail cho chúng tôi.
        /// </summary>
        public static string SendMailToUs {
            get {
                return ResourceManager.GetString("SendMailToUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện video.
        /// </summary>
        public static string VideoLibrary {
            get {
                return ResourceManager.GetString("VideoLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả dự án.
        /// </summary>
        public static string ViewAllProject {
            get {
                return ResourceManager.GetString("ViewAllProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
    }
}
